#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi


#
# History
#
HISTSIZE=100000                   # The maximum number of events to save in the internal history.
SAVEHIST=100000                   # The maximum number of events to save in the history file.
BANG_HIST=true
EXTENDED_HISTORY=true
INC_APPEND_HISTORY=true
SHARE_HISTORY=false
HIST_EXPIRE_DUPS_FIRST=true
HIST_IGNORE_DUPS=true
# HIST_IGNORE_ALL_DUPS=true
HIST_FIND_NO_DUPS=true
HIST_IGNORE_SPACE=true
HIST_SAVE_NO_DUPS=false
HIST_VERIFY=true
HIST_BEEP=true
